# Generated by Django 3.2.13 on 2022-05-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
    ]
