# Generated by Django 3.2.13 on 2022-04-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_photo_url',
        ),
    ]
