# Generated by Django 3.2.13 on 2022-05-08 21:21

import api.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_id_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[api.common.validators.is_national_id]),
        ),
    ]
