# Generated by Django 3.2.13 on 2022-04-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20220421_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cases.case'),
        ),
    ]
