# Generated by Django 3.2.13 on 2022-06-04 15:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_casecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encoding', to='cases.casephoto')),
            ],
        ),
    ]
