# Generated by Django 3.2.13 on 2022-05-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20220508_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casematch',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casematch',
            name='match',
        ),
        migrations.AddField(
            model_name='casematch',
            name='found',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='cases.case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casematch',
            name='missing',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='missing_matches', to='cases.case'),
            preserve_default=False,
        ),
    ]
