# Generated by Django 3.2.13 on 2022-05-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20220510_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='thumbnail',
            field=models.URLField(default='https://picsum.photos/200/300'),
            preserve_default=False,
        ),
    ]
