# Generated by Django 3.2.13 on 2022-05-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('cases', '0008_case_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casephoto',
            name='url',
        ),
        migrations.AddField(
            model_name='casephoto',
            name='file',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='thumbnail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
